.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_80000400
    /* 1000 80000400 3C0A8000 */  lui        $t2, %hi(func_800010D8)
    /* 1004 80000404 3C1D8011 */  lui        $sp, %hi(D_801126B0)
    /* 1008 80000408 254A10D8 */  addiu      $t2, $t2, %lo(func_800010D8)
    /* 100C 8000040C 01400008 */  jr         $t2
    /* 1010 80000410 27BD26B0 */   addiu     $sp, $sp, %lo(D_801126B0)
    /* 1014 80000414 00000000 */  nop
    /* 1018 80000418 00000000 */  nop
    /* 101C 8000041C 00000000 */  nop
    /* 1020 80000420 00000000 */  nop
    /* 1024 80000424 00000000 */  nop
    /* 1028 80000428 00000000 */  nop
    /* 102C 8000042C 00000000 */  nop
    /* 1030 80000430 00000000 */  nop
    /* 1034 80000434 00000000 */  nop
    /* 1038 80000438 00000000 */  nop
    /* 103C 8000043C 00000000 */  nop
    /* 1040 80000440 00000000 */  nop
    /* 1044 80000444 00000000 */  nop
    /* 1048 80000448 00000000 */  nop
    /* 104C 8000044C 00000000 */  nop
